# Clippy configuration for V8Ray Core

# Lint levels
warn-on-all-wildcard-imports = true
disallowed-methods = [
    # Disallow unwrap() in production code
    "std::option::Option::unwrap",
    "std::result::Result::unwrap",
    # Disallow expect() with static strings
    "std::option::Option::expect",
    "std::result::Result::expect",
]

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Type complexity threshold
type-complexity-threshold = 250

# Too many arguments threshold
too-many-arguments-threshold = 7

# Too many lines threshold
too-many-lines-threshold = 100

# Avoid breaking exported API
avoid-breaking-exported-api = true

# Allow certain lints for development
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true
