# Rustfmt configuration for V8Ray Core
# 只使用稳定版特性，移除 nightly-only 选项

# Edition
edition = "2021"

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
reorder_imports = true

# Functions
# fn_args_layout 已废弃，使用 fn_params_layout
# 但 fn_params_layout 也是 nightly-only，所以移除

# Misc
remove_nested_parens = true
use_small_heuristics = "Default"
newline_style = "Unix"

# 以下选项需要 nightly，已移除:
# - imports_granularity = "Crate"
# - group_imports = "StdExternalCrate"
# - brace_style = "SameLineWhere"
# - control_brace_style = "AlwaysSameLine"
# - comment_width = 80
# - wrap_comments = true
# - format_code_in_doc_comments = true
# - doc_comment_code_block_width = 80
# - format_strings = true
# - format_macro_matchers = true
# - format_macro_bodies = true
