// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field


// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

import 'bridge/api.dart';
import 'config.dart';
import 'frb_generated.dart';
import 'lib.dart';




                abstract class V8RayBridgeApiImplPlatform extends BaseApiImpl<V8RayBridgeWire> {
                  V8RayBridgeApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ValuePtr => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;



                  @protected AnyhowException dco_decode_AnyhowException(raw);

@protected Value dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(raw);

@protected DateTime dco_decode_Chrono_Utc(raw);

@protected Map<String, Value> dco_decode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(raw);

@protected Map<String, String> dco_decode_Map_String_String_None(raw);

@protected Value dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(raw);

@protected String dco_decode_String(raw);

@protected bool dco_decode_bool(raw);

@protected Value dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(raw);

@protected ConfigInfo dco_decode_box_autoadd_config_info(raw);

@protected GrpcSettings dco_decode_box_autoadd_grpc_settings(raw);

@protected PlatformInt64 dco_decode_box_autoadd_i_64(raw);

@protected ProxyServerConfig dco_decode_box_autoadd_proxy_server_config(raw);

@protected StreamSettings dco_decode_box_autoadd_stream_settings(raw);

@protected TlsSettings dco_decode_box_autoadd_tls_settings(raw);

@protected int dco_decode_box_autoadd_u_32(raw);

@protected WsSettings dco_decode_box_autoadd_ws_settings(raw);

@protected ConfigInfo dco_decode_config_info(raw);

@protected ConnectionInfo dco_decode_connection_info(raw);

@protected ConnectionStatus dco_decode_connection_status(raw);

@protected GrpcSettings dco_decode_grpc_settings(raw);

@protected int dco_decode_i_32(raw);

@protected PlatformInt64 dco_decode_i_64(raw);

@protected List<String> dco_decode_list_String(raw);

@protected List<ConfigInfo> dco_decode_list_config_info(raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(raw);

@protected List<(String,Value)> dco_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(raw);

@protected List<(String,String)> dco_decode_list_record_string_string(raw);

@protected List<ServerInfo> dco_decode_list_server_info(raw);

@protected List<SubscriptionInfo> dco_decode_list_subscription_info(raw);

@protected String? dco_decode_opt_String(raw);

@protected Value? dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(raw);

@protected GrpcSettings? dco_decode_opt_box_autoadd_grpc_settings(raw);

@protected PlatformInt64? dco_decode_opt_box_autoadd_i_64(raw);

@protected StreamSettings? dco_decode_opt_box_autoadd_stream_settings(raw);

@protected TlsSettings? dco_decode_opt_box_autoadd_tls_settings(raw);

@protected int? dco_decode_opt_box_autoadd_u_32(raw);

@protected WsSettings? dco_decode_opt_box_autoadd_ws_settings(raw);

@protected ProxyProtocol dco_decode_proxy_protocol(raw);

@protected ProxyServerConfig dco_decode_proxy_server_config(raw);

@protected (String,Value) dco_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(raw);

@protected (String,String) dco_decode_record_string_string(raw);

@protected ServerInfo dco_decode_server_info(raw);

@protected StreamSettings dco_decode_stream_settings(raw);

@protected SubscriptionInfo dco_decode_subscription_info(raw);

@protected TlsSettings dco_decode_tls_settings(raw);

@protected TrafficStats dco_decode_traffic_stats(raw);

@protected int dco_decode_u_16(raw);

@protected int dco_decode_u_32(raw);

@protected BigInt dco_decode_u_64(raw);

@protected int dco_decode_u_8(raw);

@protected void dco_decode_unit(raw);

@protected BigInt dco_decode_usize(raw);

@protected WsSettings dco_decode_ws_settings(raw);

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

@protected Value sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(SseDeserializer deserializer);

@protected DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

@protected Map<String, Value> sse_decode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(SseDeserializer deserializer);

@protected Map<String, String> sse_decode_Map_String_String_None(SseDeserializer deserializer);

@protected Value sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected Value sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(SseDeserializer deserializer);

@protected ConfigInfo sse_decode_box_autoadd_config_info(SseDeserializer deserializer);

@protected GrpcSettings sse_decode_box_autoadd_grpc_settings(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

@protected ProxyServerConfig sse_decode_box_autoadd_proxy_server_config(SseDeserializer deserializer);

@protected StreamSettings sse_decode_box_autoadd_stream_settings(SseDeserializer deserializer);

@protected TlsSettings sse_decode_box_autoadd_tls_settings(SseDeserializer deserializer);

@protected int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

@protected WsSettings sse_decode_box_autoadd_ws_settings(SseDeserializer deserializer);

@protected ConfigInfo sse_decode_config_info(SseDeserializer deserializer);

@protected ConnectionInfo sse_decode_connection_info(SseDeserializer deserializer);

@protected ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer);

@protected GrpcSettings sse_decode_grpc_settings(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

@protected List<String> sse_decode_list_String(SseDeserializer deserializer);

@protected List<ConfigInfo> sse_decode_list_config_info(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected List<(String,Value)> sse_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(SseDeserializer deserializer);

@protected List<(String,String)> sse_decode_list_record_string_string(SseDeserializer deserializer);

@protected List<ServerInfo> sse_decode_list_server_info(SseDeserializer deserializer);

@protected List<SubscriptionInfo> sse_decode_list_subscription_info(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected Value? sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(SseDeserializer deserializer);

@protected GrpcSettings? sse_decode_opt_box_autoadd_grpc_settings(SseDeserializer deserializer);

@protected PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

@protected StreamSettings? sse_decode_opt_box_autoadd_stream_settings(SseDeserializer deserializer);

@protected TlsSettings? sse_decode_opt_box_autoadd_tls_settings(SseDeserializer deserializer);

@protected int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

@protected WsSettings? sse_decode_opt_box_autoadd_ws_settings(SseDeserializer deserializer);

@protected ProxyProtocol sse_decode_proxy_protocol(SseDeserializer deserializer);

@protected ProxyServerConfig sse_decode_proxy_server_config(SseDeserializer deserializer);

@protected (String,Value) sse_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(SseDeserializer deserializer);

@protected (String,String) sse_decode_record_string_string(SseDeserializer deserializer);

@protected ServerInfo sse_decode_server_info(SseDeserializer deserializer);

@protected StreamSettings sse_decode_stream_settings(SseDeserializer deserializer);

@protected SubscriptionInfo sse_decode_subscription_info(SseDeserializer deserializer);

@protected TlsSettings sse_decode_tls_settings(SseDeserializer deserializer);

@protected TrafficStats sse_decode_traffic_stats(SseDeserializer deserializer);

@protected int sse_decode_u_16(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected BigInt sse_decode_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected BigInt sse_decode_usize(SseDeserializer deserializer);

@protected WsSettings sse_decode_ws_settings(SseDeserializer deserializer);

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(Value self, SseSerializer serializer);

@protected void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

@protected void sse_encode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(Map<String, Value> self, SseSerializer serializer);

@protected void sse_encode_Map_String_String_None(Map<String, String> self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(Value self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(Value self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_config_info(ConfigInfo self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_grpc_settings(GrpcSettings self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_i_64(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_proxy_server_config(ProxyServerConfig self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_stream_settings(StreamSettings self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_tls_settings(TlsSettings self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_ws_settings(WsSettings self, SseSerializer serializer);

@protected void sse_encode_config_info(ConfigInfo self, SseSerializer serializer);

@protected void sse_encode_connection_info(ConnectionInfo self, SseSerializer serializer);

@protected void sse_encode_connection_status(ConnectionStatus self, SseSerializer serializer);

@protected void sse_encode_grpc_settings(GrpcSettings self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer);

@protected void sse_encode_list_config_info(List<ConfigInfo> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(List<(String,Value)> self, SseSerializer serializer);

@protected void sse_encode_list_record_string_string(List<(String,String)> self, SseSerializer serializer);

@protected void sse_encode_list_server_info(List<ServerInfo> self, SseSerializer serializer);

@protected void sse_encode_list_subscription_info(List<SubscriptionInfo> self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(Value? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_grpc_settings(GrpcSettings? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_i_64(PlatformInt64? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_stream_settings(StreamSettings? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_tls_settings(TlsSettings? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_ws_settings(WsSettings? self, SseSerializer serializer);

@protected void sse_encode_proxy_protocol(ProxyProtocol self, SseSerializer serializer);

@protected void sse_encode_proxy_server_config(ProxyServerConfig self, SseSerializer serializer);

@protected void sse_encode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value((String,Value) self, SseSerializer serializer);

@protected void sse_encode_record_string_string((String,String) self, SseSerializer serializer);

@protected void sse_encode_server_info(ServerInfo self, SseSerializer serializer);

@protected void sse_encode_stream_settings(StreamSettings self, SseSerializer serializer);

@protected void sse_encode_subscription_info(SubscriptionInfo self, SseSerializer serializer);

@protected void sse_encode_tls_settings(TlsSettings self, SseSerializer serializer);

@protected void sse_encode_traffic_stats(TrafficStats self, SseSerializer serializer);

@protected void sse_encode_u_16(int self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_usize(BigInt self, SseSerializer serializer);

@protected void sse_encode_ws_settings(WsSettings self, SseSerializer serializer);
                }
                


// Section: wire_class

class V8RayBridgeWire implements BaseWire {
            V8RayBridgeWire.fromExternalLibrary();

            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(int ptr) => wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(ptr);

void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(int ptr) => wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(ptr);
        }
        @JS('wasm_bindgen') external V8RayBridgeWasmModule get wasmModule;

        @JS() @anonymous extension type V8RayBridgeWasmModule._(JSObject _) implements JSObject {
            external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(int ptr);

external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(int ptr);
        }
        