// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'frb_generated.dart';

/// Platform capabilities
class PlatformCapabilities {
  const PlatformCapabilities({
    required this.systemProxy,
    required this.vpnMode,
    required this.tunMode,
    required this.autoStart,
  });

  /// Supports system proxy
  final bool systemProxy;

  /// Supports VPN mode
  final bool vpnMode;

  /// Supports TUN mode
  final bool tunMode;

  /// Supports auto start
  final bool autoStart;

  @override
  int get hashCode =>
      systemProxy.hashCode ^
      vpnMode.hashCode ^
      tunMode.hashCode ^
      autoStart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlatformCapabilities &&
          runtimeType == other.runtimeType &&
          systemProxy == other.systemProxy &&
          vpnMode == other.vpnMode &&
          tunMode == other.tunMode &&
          autoStart == other.autoStart;
}

/// Platform information
class PlatformInfo {
  const PlatformInfo({
    required this.os,
    required this.arch,
    required this.version,
    required this.capabilities,
  });

  /// Operating system name
  final String os;

  /// Architecture
  final String arch;

  /// OS version
  final String version;

  /// Platform capabilities
  final PlatformCapabilities capabilities;

  @override
  int get hashCode =>
      os.hashCode ^ arch.hashCode ^ version.hashCode ^ capabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlatformInfo &&
          runtimeType == other.runtimeType &&
          os == other.os &&
          arch == other.arch &&
          version == other.version &&
          capabilities == other.capabilities;
}
