name: v8ray
description: V8Ray - Cross-platform Xray Core client built with Flutter and Rust
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # UI Components
  cupertino_icons: ^1.0.6

  # Networking
  dio: ^5.4.0

  # Storage
  shared_preferences: ^2.2.2

  # Utilities
  path_provider: ^2.1.2

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: any

  # JSON
  json_annotation: ^4.8.1

  # Logging
  logger: ^2.0.2+1
  go_router: ^16.2.4
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^2.6.1

  # Flutter Rust Bridge
  flutter_rust_bridge: ^2.11.0
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^3.1.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.6

  # Icon Generation
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    # - assets/config/  # 暂未创建，后续添加

  # Fonts will be added later
  # fonts:

# Platform specific configurations
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#2196F3"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#2196F3"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo_android12.png
    color: "#2196F3"
